Add TESTING.md and Makefile
tumblr/genesis pull request #72
Opened 2017-07-06 13:56 UTC by nshalman

Per feedback in #67 this is the beginning of a TESTING.md and the Makefile that was used to test the changes in #67.

2017-07-06 15:13 UTC, byxorna requested changes
Generally looks good, but makes assumptions about the system the makefile is running on. Some tweaks and it should be good to go! Thanks for this changeset!

2017-07-06 15:13 UTC, byxorna commented on Makefile
> +	sudo docker run --name $(CONTAINER) --privileged=true -v $(PWD)/$@:/output $(BUILDER)
assuming things about the environment is not cool. how do you know this is not being run on a mac or linux box where the user has write permissions to the docker socket? or that sudo is even the privilege escalation tool in use? please remove the use of sudo and let the underlying tools either succeed or fail due to lack of permissions.

2017-07-06 15:13 UTC, byxorna commented on Makefile
> +	sudo losetup -a | cut -d: -f1 | xargs -r -n 1 sudo losetup -d
losetup doesnt exist on OSX, so this is a pretty huge assumption. Personally I build images in docker for mac and dont need this hack, or need to run it in the hyve VM instead.

2017-07-06 15:13 UTC, byxorna commented on Makefile
> +run-serial: output
I think the test targets should all be prefixed by `test-` so its clear what their intent is (clearer than reading comments in the makefile)

2017-07-07 17:19 UTC, nshalman commented
Not quite where things should be for a Mac (e.g. if on a Mac and Docker VM is not running it will think it needs sudo...)

2017-07-07 18:10 UTC, nshalman commented
Well, it's not pretty, but I didn't want to have to resort to some sort of configure script.
Based on my own testing on both a Mac and a Linux box, this should be both defensive about making sure Docker is running, and capable of using sudo only when needed.

The test-* targets are also hidden when not on Linux.

Let me know what you think.

2017-07-11 20:43 UTC, roymarantz commented
Generally speaking I'm not wild about Makefile running sudo.  Why not assume that the invoking user has permissions to run docker directly?

2017-07-11 20:45 UTC, nshalman commented
Because mine doesn't on my Linux box.

2020-07-17 14:25 UTC, closed without merging